### ISSUE TITLE
Subcontract issues

### ISSUE THREAD

**Issue by Rgottsch1** [agritheory/inventory_tools#38]
I've setup a FG part # with two outside vendor operations.  Attached are the BOMs setup and details.  The issue is material consumption for manufacture did not require handling units entry (the material transfer for manufacturing did).  I tried to cancel the material consumption for manufacture entry and I have an error that is reflected on the attached sheet.
[Subcontract Issue #1.docx](https://github.com/agritheory/inventory_tools/files/12921094/Subcontract.Issue.1.docx)

**Comment by HKuz** [comment]
@Rgottsch1  - I was able to replicate this issue using your data, then I also see it happening in my BEAM site. I'm going to close this issue and move it over to that repository with some additional notes.
