### ISSUE TITLE
Manufacturing Over/Under Production

### ISSUE THREAD

**Issue by agritheory** [agritheory/inventory_tools#40]
Allow a per-BOM, with fallback to Inventory Tools Settings, value to be set for over/under production of finished goods.

**Comment by fproldan** [comment]
@agritheory 
This feature is a per-BOM replacement for this configuration?


![Captura de pantalla 2024-01-11 a la(s) 12 15 19](https://github.com/agritheory/inventory_tools/assets/4945122/fcbb6b27-27bf-4d61-92a6-8df27c319f77)

**Comment by agritheory** [comment]
@fproldan Yes but that isn't the whole story. This setting isn't actually respected downstream, so that part needs to be implemented as well. I have some notes on this I will send separately.
