### ISSUE TITLE
Make Creation of Job Card(s) on Submit of Work Order configurable 

### ISSUE THREAD

**Issue by agritheory** [agritheory/inventory_tools#47]
User should be able to specify by BOM (new custom field with allow after submit), with a fallback in Inventory Tools Settings if the associated Job Card(s) should be created automatically.

**Comment by agritheory** [comment]
@fproldan The setting for this feature seems to have disappeared from Inventory Tools Settings. Can you figure out what has happened?

**Comment by fproldan** [comment]
@agritheory 

I see the settings [in the code](https://github.com/agritheory/inventory_tools/blob/version-14/inventory_tools/inventory_tools/doctype/inventory_tools_settings/inventory_tools_settings.json#L104-L114) and in a updated instance 

![Captura de pantalla 2024-06-11 a la(s) 11 13 55 a  m](https://github.com/agritheory/inventory_tools/assets/4945122/0e9b638e-8d7b-4f8b-9d00-030e67eacf73)


[Same for v15](https://github.com/agritheory/inventory_tools/blob/version-15/inventory_tools/inventory_tools/doctype/inventory_tools_settings/inventory_tools_settings.json#L106-L117)
