### ISSUE TITLE
Aggregate and/or Split Quotations into multiple Sales Orders

### ISSUE THREAD

**Issue by agritheory** [agritheory/inventory_tools#55]
Using a report workflow similar to Material Demand. Allow for splitting partial quantities to different sales orders. In a multi-company scenario, allow the Sales Orders to be split. 

User story/ demo data to add:
Multiple Quotations from the same customer, including some overlapping items with differing time requirements

Multi company scenario - where the complete order can be fulfilled by fulfilling from two companies / warehouses

**Comment by agritheory** [comment]
Report to named "Quotation Demand"

**Comment by federicocalvo** [comment]
@agritheory 
here are some questions
- Should the SO be done in draft? In case they are validated, it would be necessary to define what we can take for delivery_date
The options to contemplate for multicompany would be:
- If a quotation company A, a SO from company A and a SO from company B can be made
- From a quotation from company A and a quotation from company B, make ONE SO to company B for both items.

**Comment by agritheory** [comment]
@federicocalvo Very good questions

> Should the SO be done in draft?

Yes, I think so

> In case they are validated, it would be necessary to define what we can take for `delivery_date` 

I think we have to use the SO date + lead time as defined on the item. I didn't realize there isn't a delivery date on the Quotation doctype which seems like an oversight

> The options to contemplate for multicompany would be:
> If a quotation company A, a SO from company A and a SO from company B can be made

Yes by selecting different lines or a reduced qty 

> From a quotation from company A and a quotation from company B, make ONE SO to company B for both items.

Yes, though I think it should be added as two lines to `items` in the SO with references to the different lines from the different Quotations

**Comment by federicocalvo** [comment]
I leave this to be done in this issue as a note, but it is also useful for demand material. In the tests add:

-Creation of a company
- Material demand of this company (with cocoplum between products).
- Quotations of this company with more than one item.

**Comment by federicocalvo** [comment]
@agritheory the behavior of the date then is, **TODAY** + whatever you have configured in the item in the **Lead Time in days** field, and in case you do not have anything in this field, it will place today's day.

Some considerations:
-The Lead Time in days field belongs to Purchasing, it is strange to me that there is not the same in sales, I do not know if you can consider adding this simple term to use it especially in this issue.

-The delivery date is fundamental when defining SO, it could be an optional in the pop, and in case of selecting a date in question, it overwrites the previous behavior, leaving all cases ready.

Off topic: We leave a comment of issue 17 (Material Demand), that in case we agree, we can replicate multi-company behavior in Quotation Demand.
