### ISSUE TITLE
Renaming a Specification Attribute will orphan linked values

### ISSUE THREAD

**Issue by agritheory** [agritheory/inventory_tools#76]
We need to detect the change on specification attribute name change to update linked values. A common example would be something like Changing "item Group" to "Product Type" or "Category"

**Comment by bhattdevarsh** [comment]
https://github.com/agritheory/inventory_tools/assets/58166671/d7d40ca5-3e02-4924-9123-5eead966f7ee

**Comment by agritheory** [comment]
That's exactly what I had in mind.
