### ISSUE TITLE
Faceted search improvements

### ISSUE THREAD

**Issue by bhattdevarsh** [agritheory/inventory_tools#95]
- [x] Name prompt for Specification document
- [x] Validate repeating attribute under dialogue
![image](https://github.com/agritheory/inventory_tools/assets/58166671/6219938f-e88f-4aae-8c64-53b07742361d)

- [x] Not able to delete row under dialogue 
![image](https://github.com/agritheory/inventory_tools/assets/58166671/ec2881c7-d63e-49a4-9591-511e9ec52f04)

- [x] Should Specification Values have reference doctype and docname?
![image](https://github.com/agritheory/inventory_tools/assets/58166671/5aee473e-0cfe-43e6-ac7d-173968cdaa00)

**Comment by agritheory** [comment]
Resolved with 06ed07483f69dfcca5f809be496ee37bd4d4cc8b on `faceted_search`
